server:
  port: 8818

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:oci-helper.db
    druid:
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1

mybatis-plus:
  mapper-locations: classpath*:com/yohann/ocihelper/mapper/xml/*.xml

# 密钥文件存放目录（如果是docker部署则不用修改）
oci-cfg:
  key-dir-path: /app/oci-helper/keys

# web登录管理员账号密码
web:
  account: admin
  password: mypwd

# TG接收消息通知的机器人token和个人ID （可选）
tg-cfg:
  token: xxxx:xxxx
  chat-id: xxxxxx