server:
  port: 8818

# --------------------------------------- 用户自定义修改项 ------------------------------------
# web登录管理员账号密码
web:
  account: yohann
  password: yohann
# --------------------------------------- 用户自定义修改项 ------------------------------------

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:oci-helper.db
    druid:
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
  sql:
    init:
      mode: always

mybatis-plus:
  mapper-locations: classpath*:com/yohann/ocihelper/mapper/xml/*.xml

logging:
  pattern:
    # console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %msg%n"
  level:
    com.oracle.bmc: error
    c.o.b.h.c.j: error

# 密钥文件存放目录（如果是docker部署则不用修改）
oci-cfg:
  key-dir-path: /app/oci-helper/keys