server:
  port: 8818

# --------------------------------------- 用户自定义修改项 ------------------------------------
# web登录管理员账号密码
web:
  account: yohann
  password: yohann
# --------------------------------------- 用户自定义修改项 ------------------------------------

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:oci-helper.db
    druid:
      pool-prepared-statements: false     # 禁用 PreparedStatement 缓存，即每次都重新创建
      max-pool-prepared-statement-per-connection-size: -1 # 表示不限制每个连接缓存多少个
      validation-query: SELECT 1         # 设置校验语句
      initial-size: 1                    # 初始化连接数
      min-idle: 1                        # 最小空闲连接数
      max-active: 10                     # 最大连接数，推荐根据并发需求调整
      max-wait: 5000                     # 最大等待时间（毫秒）
      time-between-eviction-runs-millis: 60000 # 检测空闲连接的间隔时间
      min-evictable-idle-time-millis: 300000  # 最小空闲时间（毫秒）
  sql:
    init:
      mode: always

mybatis-plus:
  mapper-locations: classpath*:com/yohann/ocihelper/mapper/xml/*.xml

logging:
  pattern:
    # console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %msg%n"
  level:
    com.oracle.bmc: error
    c.o.b.h.c.j: error

# 密钥文件存放目录（如果是docker部署则不用修改）
oci-cfg:
  key-dir-path: /app/oci-helper/keys
#  key-dir-path: C:\Users\Yohann\Desktop